spring.application.name=mutuelle-backend

# Database Configuration
spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/ORCLPDB
spring.datasource.username=gestion_mutuelle
spring.datasource.password=1234
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect

# JWT Configuration
mutuelle.app.jwtSecret=mutuelleSecretKeyWithEnoughLengthForHS512Algorithm1234567890_ExtraLengthForSecurity64Chars_ExtraLengthForSecurity64Chars
mutuelle.app.jwtExpirationMs=86400000

# Server Configuration
server.port=8081

# Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ouhsaineoumaima1@gmail.com
spring.mail.password=onjefalacjozzjhd
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
